### ISSUE TITLE
Error: There was a failure invoking your skill with text input, please try again.

### ISSUE THREAD

**Issue by chollan** [josephschmitt/alexa-libby#1]
I am using your walkthrough, which is very well documented may I add, yet i'm getting the 'failure invoking your skill with text input' error.

steps I followed:
1. clone your repo to my local computer (node 6.5.0 installed)
2. change the config file to point to my pvr
3. run npm start and recieve a successful response from my pvr
4. run npm run package and upload the zip to lambda.
5. follow the set up steps you provided on the amazon developer portal.
6. attempt to test with text and I get the error response.

it's worth noting that if I type "start libby" as the invocation word, I get a successful response with the help text from libby.  

is there anything else you need from me?

**Comment by chollan** [comment]
this may also be something I take up with amazon... just let me know if that's the case

**Comment by chollan** [comment]
it appears this was an issue on amazon's side.  sorry about that.

**Comment by josephschmitt** [comment]
@chollan oh awesome, glad it wasn't on my end 💯

**Comment by josephschmitt** [comment]
@chollan so do you have this all up and running? Still looking for the first person to have had success

**Comment by chollan** [comment]
@josephschmitt yeah, i got it working just great!  i'm not publishing it because it has my pvr settings in it, but it still works in development mode.  Nice project!  #10outof10 #woulduseagain
