### ISSUE TITLE
Getting request identifier errors since updating default.json

### ISSUE THREAD

**Issue by bsollenb54** [josephschmitt/alexa-libby#12]
I'm getting the following response when I invoke the skill: Request Identifier: amzn1.echo-api.request.572a6d44-e55f-46a5-a08b-b955591aac77

Here's the default.json changes I made (quality profile and tmdb apikey updates):

{
  "alexa-libby": {
    "server": {
      "hostname": "http://server.com"
    },
    "movies": {
      "provider": "radarr",
      "server": {
        "apiKey": "dkekdkejdkejdke123345",
        "port": 7878
      },
      "quality": "All"
    },
    "shows": {
      "provider": "sonarr",
      "server": {
        "apiKey": "dkekdkejdkejdke123345",
        "port": 8989
      },
      "quality": "All"
    },
    "artwork": {
      "tmdbApiKey": "dkekdkejdkejdke123345"
    }	
  }
}

The most peculiar part is the very first request I made downloaded a show off of sonarr but then I started getting this error again over and over.

Testing the skill in the Alexa Skills Kit returns a "the remote endpoint could not be reached" but I can access my ports for Sonarr and Radarr via Chrome, so I'm not sure what the issue is. Any thoughts?

**Comment by jmseaton** [comment]
Did your public IP address change?


------
Jared Seaton

twitter.com/jmseaton

**Comment by bsollenb54** [comment]
No, it's still accessible via my DDNS http from a Chrome browser, both on my phone and on my work's wifi. I came back to testing it and now get the following error when I entered "ask sonar if the movie the dark knight is on the list" (sonar is my invocation name instead of libby)

Error: There was a failure invoking your skill with text input, please try again.

Tried a few other utterances after that but same error. Thoughts?

**Comment by bsollenb54** [comment]
Oh also, I just deleted and recreated my lambda function just in case. Still the same issues.

**Comment by bsollenb54** [comment]
Hmmm - it works now. I did two things differently.

1) I re-built my config file from scratch top-to-bottom. Doing a compare it still looks structurally the same as I had it in the first post:
{
"alexa-libby": {
"server": {
"hostname": "http://my.server.com"
},
"movies": {
"provider": "radarr",
"server": {
"apiKey": "abc123",
"port": 7878
},
"quality": "All"
},
"shows": {
"provider": "sonarr",
"server": {
"apiKey": "abc123",
"port": 8989
},
"quality": "All"
},
"artwork": {
"tmdbApiKey": "abc123"
}
}
}

2) I re-zipped and uploaded my pre-packaged .zip with alexa-libbyv2.zip. Maybe re-saving over the same .zip file name wasn't making it happy before.

Either way. Working well now and it's cool to see TMDB poster art on my Echo Show!
