### ISSUE TITLE
An error occurred: error

### ISSUE THREAD

**Issue by akhan23wgu** [josephschmitt/alexa-libby#15]
I might say these are my favorite types of errors! Whenever I request something, I get the response below.

My config has both SSL enabled on sonarr and radarr, different hostnames.

#####Error response#####

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak>An error occured: Error</speak>"
    },
    "speechletResponse": {
      "outputSpeech": {
        "ssml": "<speak>An error occured: Error</speak>"
      },
      "directives": [],
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}

#####default.json#######

{
  "alexa-libby": {
    "server": {},
    "movies": {
      "provider": "radarr",
      "server": {
        "apiKey": "API string",
        "hostname": "https://movies.domain.xyz",
        "port": 443
      }
	  "quality": "HD-720p"
    },
    "shows": {
      "provider": "sonarr",
      "server": {
        "apiKey": "API string",
        "hostname": "https://tv.domain.xyz",
        "port": 443
      }
	  "quality": "HDTV-720p"
    }
  }
}

**Comment by jmseaton** [comment]
Not sure if it's related, but if you're using SSL, the cert has to be from
a CA that amazon trusts.  Any of the big vendors.  You can't use
self-signed.  It took me some time to diagnose myself, and i don't recall
the exact error I was getting.


------
Jared Seaton

twitter.com/jmseaton

**Comment by akhan23wgu** [comment]
I don't know what the real issue was, maybe an screw up in the config file. I redid it, and it works! :)
