### ISSUE TITLE
Radarr API updated, no longer works

### ISSUE THREAD

**Issue by BenStein1** [josephschmitt/alexa-libby#25]
Connections to Radarr return:
**From the Radarr Log**
18-3-8 19:00:13.1|Debug|Api|[GET] /api/movies/lookup?term=Zulu: 404.NotFound (0 ms)

**From the Alexa Skill Log**
{
	"body": {
		"version": "1.0",
		"response": {
			"outputSpeech": {
				"type": "SSML",
				"ssml": "<speak>An error occured: Error: NotFound</speak>"
			},
			"directives": [],
			"shouldEndSession": true
		},
		"sessionAttributes": {}
	}
}

From what I have gathered is that the Radarr project has been updated and been distanced from Sonarr somewhat. So the API call to '**movies/lookup**' or rather just the api command '**movies**' no longer exists. The command is now just '**movie**' (no s), and as far as I can tell, '**lookup**' is also gone.

**Comment by brettg0396** [comment]
There a hotfix we can implement ourselves, or is there more to it than just a find-and-replace in this instance? Haven't pored over the code much.

**Comment by markrennie71** [comment]
I was just about to install this (again) but is it worth it now that Radarr is broken?

**Comment by brettg0396** [comment]
Sonarr still works with alexa-libby, but until the devs update it to work
with the new radarr api (which sounds simple enough since it's a change in
path) then the radarr functionality is borked, so.

**Comment by markrennie71** [comment]
if it is only a small change.. it isn't hard just change these 2
export async function search(query) {
  await loadQualityProfiles();
  const resp = await radarr().get('movies/lookup', {term: query});

  describe('.search()', () => {
    beforeEach(() => {
      apiStub.withArgs('movies/lookup', {term: 'assassin'}).resolves([
        sampleMoviesResponse[1]
      ]);
    });

**Comment by brettg0396** [comment]
Maybe. I've been quite busy with university as of late, so what I did was
just run a find-and-replace for the old path, with the new path on all
files in the source with notepad++ and that didn't work, but I don't think
it caught anything in actual source. Which file is that? Try it and tell me
if it works. Either way I'll give it a go after work and get back to you.

**Comment by markrennie71** [comment]
radarr.js in src\api.. I'll have a play later. might not be as simple as I 1st thought.

**Comment by brettg0396** [comment]
Yeah, that might have been the one I tried. I'll look deeper into the code
when I get home, but yeah, I thought the same.

**Comment by almostepic89** [comment]
If you build from source you only need to change one line to make it work again. Then just build from source and upload the new zip archive to the lambda function.

/src/api/radarr.js -> line 58 - Remove the 's' in movies. 
`const resp = await radarr().get('movie/lookup', {term: query});`

I have also attached a copy of the .js file from the dist folder. Should be able to just replace the radarr.js in dist/api/.
[radarr.zip](https://github.com/josephschmitt/alexa-libby/files/1844983/radarr.zip)

**Comment by markrennie71** [comment]
thanks for this.. well looks like I still cannot use this due to being in the UK.. arse

"AMAZON.Movie"are not currently available for en_GB

**Comment by almostepic89** [comment]
change it to AMAZON.literal and you should still be able to use it.

**Comment by markrennie71** [comment]
I remember I tried that before and it didn't work.. so I guess just changing to           "type": "AMAZON.literal", but that doesn't work and I cannot work out how on earth I am supposed to generate a new list of samples that I presume I need to add in it as well? over my head I think :(

**Comment by almostepic89** [comment]
Yeah unfortunately Amazon has removed AMAZON.LITERAL from all other locals except English US and they have not added in the built in slot type of AMAZON.MOVIE or TVSHOW. At this point your best bet would be to send them a message as a feature request for it. I even tried creating a custom slot type and setting just one value since one place I read said that it would still process information if it was able to discern it from the spoken language but it doesn't seem to be picking up on anything except specified values in the custom slot type.

**Comment by almostepic89** [comment]
@markrennie71 Update - I found that if you create a custom slot and name it movieName. Then add multiple values of some random movies (I added 10 just to be safe). Then in the FindMovie and AddMovie intents you set the Slot Type to your custom slot you created so Intent Slot is movieName and slot type is movieName, it acts as a wild card and you are able to pass it literal text strings in the same sense that AMAZON.Literal does. You have to have several possible values in the custom slot type for the custom slot to then act as a wild card. I've included a copy of my Alexa JSON from the skill builder for reference.

[SkillBuilder.zip](https://github.com/josephschmitt/alexa-libby/files/1845852/SkillBuilder.zip)

edit: the invocation name was changed to miss libby as Amazon kept thinking I was saying Livy for some reason...

**Comment by brettg0396** [comment]
@almostepic89 care to elaborate on your success in building from source? I tried to do the same with up-to-date node.js and npm on Ubuntu 16.0.4 and everything built successfully (install of dependencies, packaging of the .zip) but when I go to test the skill in the Alexa Developer Console, I get an "Audio Only Response" from any query made to the skill, be it from radarr or from sonarr. It's like something has fundamentally broken which shouldn't have from altering just radarr.js. Am I doing something wrong here?

**Comment by almostepic89** [comment]
@brettg0396 that hinestly sounds more like an issue with the changes made to the radarr.js file, rather than the building. If it built and compiled the .zip file properly and you are getting a response then it seems the build was done right. Can you upload the radarr.js file as a zip and I'll take a look.

**Comment by brettg0396** [comment]
Sure thing in a bit, but it's literally just a removal of the character 's'
in 'movies/lookup' on line 58. No other change.

**Comment by almostepic89** [comment]
If thats the case then dont worry about uploading it. I'm building using Windows myself using node.js 6.? (Not at the computer at the moment but its which ever version was selected during the tutorial for the lambda server). I have noticed on rare occasion the alexa app doesn't show the json request/response but a reload of the page usually fixes it for me. I'm not very knowledgable in node.js (even the programming in JS I've been doing to add additional features is coming from my experience in PHP) so I'm not really sure I'd be able to help except to explain what I had to do to get it to build in Win 10.

**Comment by brettg0396** [comment]
Yeah I'm at a loss myself. Initially tried doing this on win10 but this
isn't my area of expertise either and I was running into some issues, so I
just decided to play it safe and do it on Linux.

**Comment by almostepic89** [comment]
In win 10 I had to modify the package.json file scripts so that "package"
only ran the second command (remove the first part where it runs prepare),
then i ran "install", "run build", "run package" each individually. It
skips some commands which rely on a package which isnt built for windows
and is skipped during the install command.

**Comment by brettg0396** [comment]
Good to know, will try that in a bit.

**Comment by mongolianmiller** [comment]
Following. I **_would_** decide to learn and implement this feature right after it doesn't work anymore. xD  I should have looked at the issue list first.

**Comment by BenStein1** [comment]
I just tested the change on line 58 to Radar.js and it indeed does work. Radarr api is connected again. Thanks folks for hunting that down. I wasn't sure where to start with that. I really appreciate the help.

**Comment by brettg0396** [comment]
Could I get a copy of the functioning .zip? Idk if my build is having
issues or what.

**Comment by BenStein1** [comment]
I just downloaded the latest compiled zip from here:
https://github.com/josephschmitt/alexa-libby/releases/tag/v1.2.0

And replaced the dist/api/radar.js with the updated on from here:
https://github.com/josephschmitt/alexa-libby/files/1844983/radarr.zip

I replaced my default.json with my personal config, re-zipped, and re-uploaded to lambda, and everything was working again.

**Comment by brettg0396** [comment]
I'll be sure to try that.
