### ISSUE TITLE
Remote endpoint could not be reached

### ISSUE THREAD

**Issue by bsollenb54** [josephschmitt/alexa-libby#5]
Hi Joseph,

I'm hitting an issue when I test my skill that the lambda response is "Remote endpoint could not be called, or the response it returned was invalid.

This was my utterance "Alexa, ask libby if the movie The Dark Knight is on the list" which yielded the lambda request:

{
  "session": {
    "sessionId": "SessionId.b33d6c7d-e5a5-4ceb-b86b-8f5c8ef02784",
    "application": {
      "applicationId": "amzn1.ask.skill.c7eb1e7e-9483-4c50-b4e0-386084becab1"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AEVVZKWG4RPCQ47NKA7C34GR5H2RV2DGBHXHPMYXZDBCVVKKEADUTQEFWA7B7GY7ZMDXV3RV2PRF4UMEQ2JOXEJTFI37ONFL6OKDRAO3VF7F7U2PPTKAG3JNV4YSZZS5MMJZRBB6BHKBN6ZPML3EKFCYQ3VWX27KJ5B5D5E5BZRX2ZQLJRU2TRTMZ6KPPCKV4SOPMQRNJFPGMWQ"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.023f81ce-0ab3-4d46-86fa-c6d089bf45cb",
    "locale": "en-US",
    "timestamp": "2017-06-28T20:27:40Z",
    "intent": {
      "name": "FindMovie",
      "slots": {
        "releaseDate": {
          "name": "releaseDate"
        },
        "movieName": {
          "name": "movieName",
          "value": "the dark knight"
        }
      }
    }
  },
  "version": "1.0"
}

Meanwhile, I tried a few different default.json configs - my setup is the same ddns hostname and the standard Sonarr and Radarr ports (8989 and 7878 respectively). I created a new lambda function from the console and uploaded the .zip with the updated default.json. Any insights into what the issue might be?

{
  "alexa-libby": {
    "server": {
      "hostname": "http://my-pvr-server.com"
    },
    "movies": {
      "provider": "radarr",
      "server": {
        "apiKey": "abcdefghijklmnopqrstuvwxyz123456",
        "port": 7878
      }
    },
    "shows": {
      "provider": "sonarr",
      "server": {
        "apiKey": "abcdefghijklmnopqrstuvwxyz123456",
        "port": 8989
      }
    }
  }
}

{
  "alexa-libby": {
    "server": {
      "hostname": "http://my-pvr-server.com"
    },
    "movies": {
      "provider": "radarr",
      "server": {
        "apiKey": "abcdefghijklmnopqrstuvwxyz123456",
        "port": 7878
      }
    },
    "shows": {
      "provider": "sonarr",
      "server": {
        "apiKey": "abcdefghijklmnopqrstuvwxyz123456",
        "port": 8989
      }
    }
  }
}

**Comment by josephschmitt** [comment]
The config you're using looks good to me. That error sounds to me like Amazon is unable to reach your server. You're sure your server is accessible from outside your network?

**Comment by bsollenb54** [comment]
yea, I accessed it from my iPhone on LTE "http://hostname:port" in Safari browser just to confirm - both Radarr and Sonarr GUIs worked.

**Comment by bsollenb54** [comment]
The lambda function size is ~95kb. Compared to a Kodi skill and Google ask skill I've gotten off github (~3 MB), the .zip seems pretty light. For comparison, your couchpotato skill (which is awesome BTW) is around 3 MB.

**Comment by josephschmitt** [comment]
@bsollenb54 try grabbing the [latest release](https://github.com/josephschmitt/alexa-libby/releases) instead, that has everything pre-packaged and ready to go except for your configuration. That clocks in at around 5MB, which is way more accurate than 95k.

**Comment by josephschmitt** [comment]
@bsollenb54 also, when re-zipping to upload to Lambda, make sure you grab everything you extracted from that release zip, it's all necessary. More info here: https://github.com/josephschmitt/alexa-libby/wiki/Using-the-Pre-packaged-Zip-File

**Comment by bsollenb54** [comment]
Lol doh - I must've renamed the github download at some point from "alexa-libby-master" to "alexa-libby) which clearly overrode the prepackaged zip (the compressed file was ~94kb, obv not the prepackaged one anymore). I redownloaded and it works like a charm now!

Cheers! You have a patreon or something? Your CP and Sonarr skills have been incredible!

**Comment by josephschmitt** [comment]
Ha, thanks, but no. I'd feel a bit queasy about taking money for working on this stuff. I mostly use it as a distraction for fun and to learn new tech. If you have anything you'd like to contribute to the project, even if it's just documentation or updating the Wiki, please do so.

Cheers.
