### ISSUE TITLE
Specify Radarr Quality Profile in Config

### ISSUE THREAD

**Issue by Hackworth** [josephschmitt/alexa-libby#6]
The qualityProfileId is always 1 (Any) and currently you have to hard code it to different ID in radarr.js line 74, it would be nice to specify the human readable profile in the config.

**Comment by josephschmitt** [comment]
I'd been trying to think how someone could specify a quality. Config seems like a decent place. How do you see it being specified? By id? Name? Both? What is there's no match? Then fall back to Any?

**Comment by Hackworth** [comment]
Name I would think, the GUI for Radarr doesn't expose the ID. Fall back to Any seems reasonable to me. I would also have an option for the root folder.

**Comment by Hackworth** [comment]
Looks like the same thing for Sonarr, it defaults to SD.

**Comment by josephschmitt** [comment]
Sounds good to me
