### ISSUE TITLE
Adding to Radarr list doesn't automatically download

### ISSUE THREAD

**Issue by Hackworth** [josephschmitt/alexa-libby#7]
Adding a movie to the Radarr list doesn't automatically download. Adding this to radarr.js line 75 makes it start downloading when added: 

```
addOptions: {
   searchForMovie: true
}
```

**Comment by josephschmitt** [comment]
Ohh, nice. Can you add this and submit a PR?

**Comment by Hackworth** [comment]
Yeah, no problem :)
